"""empty message

Revision ID: 2b7e0641334d
Revises: f76f4ae4e36a
Create Date: 2025-09-10 19:15:11.442718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7e0641334d'
down_revision: Union[str, Sequence[str], None] = 'f76f4ae4e36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_by')
    # ### end Alembic commands ###
